# Generated by Django 4.2.7 on 2023-12-15 03:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(default='product.png', upload_to=core.models.user_directory_path),
        ),
    ]
